image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки


install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
  - mkdir -p $DOCKER_CONFIG/cli-plugins
  - sudo curl -SL https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
  - sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  - sudo docker-compose up -d
  - sleep 10
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar aqa-shop.jar &
  - sleep 10

build_script:
  - chmod +x gradlew
  - ./gradlew -Ddb.url=jdbc:mysql://localhost:3306/app test --info "-Dselenide.headless=true"
