image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки


install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - sudo apt-get install docker-ce=<VERSION_STRING> docker-ce-cli=<VERSION_STRING> containerd.io docker-compose-plugin
  - sudo docker-compose up -d
  - sleep 10
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar aqa-shop.jar &
  - sleep 10

build_script:
  - chmod +x gradlew
  - ./gradlew -Ddb.url=jdbc:mysql://localhost:3306/app test --info "-Dselenide.headless=true"
